name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'shoonyawallet/package-lock.json'
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Prepare React Native app
        run: bash .github/scripts/prepare_rn_app.sh
      - name: Cache NPM (tarballs)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('shoonyawallet/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install NPM dependencies (idempotent)
        working-directory: ./shoonyawallet
        run: |
          if [ -f package-lock.json ]; then npm ci || npm install; else npm install; fi
      - name: Build Debug APK
        working-directory: ./shoonyawallet
        run: |
          chmod +x android/gradlew || true
          cd android
          ./gradlew assembleDebug --no-daemon
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: shoonyawallet/android/app/build/outputs/apk/debug/app-debug.apk
          compression-level: 0
