name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify app path
        run: |
          if [ ! -f mobile/package.json ]; then
            echo "::error:: mobile/package.json not found. Ensure 'mobile/' is committed on this branch.";
            ls -la; exit 1; fi
          ls -la mobile
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache NPM (tarballs)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('mobile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install NPM dependencies
        working-directory: ./mobile
        run: |
          if [ -f package-lock.json ]; then \
            npm ci || (echo "npm ci failed; falling back to npm install" && npm install); \
          else \
            npm install; \
          fi
      - name: Run tests (Jest)
        working-directory: ./mobile
        run: npm test -- --ci --reporters=default --watchAll=false

  build-android:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify app path
        run: |
          if [ ! -f mobile/package.json ]; then
            echo "::error:: mobile/package.json not found. Ensure 'mobile/' is committed on this branch.";
            ls -la; exit 1; fi
          ls -la mobile
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache NPM (tarballs)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('mobile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache NPM (tarballs)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('mobile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install NPM dependencies
        working-directory: ./mobile
        run: |
          if [ -f package-lock.json ]; then \
            npm ci || (echo "npm ci failed; falling back to npm install" && npm install); \
          else \
            npm install; \
          fi
      - name: Generate Trezor descriptor.json from vendored protos
        working-directory: ./mobile
        run: |
          set -euo pipefail
          PROTO_DIR=src/services/hardware/trezor/protos
          ls -la "$PROTO_DIR"
          # Ensure required protos exist (committed in repo)
          for f in options.proto messages.proto messages-common.proto messages-management.proto messages-solana.proto; do
            if [ ! -f "$PROTO_DIR/$f" ]; then
              echo "::error::$f missing in $PROTO_DIR"; exit 1;
            fi
          done
          # Generate descriptor JSON used by runtime
          npx pbjs -t json -o "$PROTO_DIR/descriptor.json" \
            "$PROTO_DIR/options.proto" \
            "$PROTO_DIR/messages-common.proto" \
            "$PROTO_DIR/messages-management.proto" \
            "$PROTO_DIR/messages.proto" \
            "$PROTO_DIR/messages-solana.proto"
      - name: Pre-bundle JS into assets
        working-directory: ./mobile
        run: |
          mkdir -p android/app/src/main/assets android/app/src/main/res
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
      - name: Build Debug APK
        working-directory: ./mobile
        run: |
          chmod +x android/gradlew || true
          cd android
          ./gradlew assembleDebug --no-daemon
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: mobile/android/app/build/outputs/apk/debug/app-debug.apk
          compression-level: 0
