name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Prepare React Native app
        run: |
          brew install rsync || true
          bash .github/scripts/prepare_rn_app.sh
      - name: Install Ruby and CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install Pods
        working-directory: ./shoonyawallet/ios
        run: |
          gem install cocoapods --no-document
          pod install --repo-update || pod install
      - name: Build iOS
        working-directory: ./shoonyawallet/ios
        run: |
          xcodebuild -workspace shoonyawallet.xcworkspace -scheme shoonyawallet -configuration Release -sdk iphonesimulator -arch x86_64 build | xcpretty

